"""Inclusão de campo respondeu na tabela Contato

Revision ID: 7604e145834c
Revises: 4f17aa83b96c
Create Date: 2025-08-03 15:07:11.215122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7604e145834c'
down_revision = '4f17aa83b96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondeu', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondeu')

    # ### end Alembic commands ###
